meta_product_name: "AssetBase"
meta_title: "AssetBase - All your assets in one place"
meta_description: "AssetBase enables you to to track all your assets in a single app. No matter if stocks, crypto, NFTs or sneakers. The hassle-free up that allows you to make better investments. "
meta_image: "logo.png"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
